### ISSUE TITLE
Failed to run example file.

### ISSUE THREAD

**Issue by lugy-bupt** [mildsunrise/node_bpfcc#1]
Hi,

I tried the example files on Ubuntu 20.04 and failed, would you please help to check the root cause?

The output is below.
```
bizconf@bizconf:~/work/bpf-node$ tsc test.ts --downlevelIteration
bizconf@bizconf:~/work/bpf-node$ node test.js 
Loading program...
bpf: Failed to load program: Operation not permitted

/home/bizconf/work/bpf-node/node_modules/bpfcc/dist/exception.js:26
    throw new BCCError(status.code, status.msg);
    ^

BCCError: Failed to load kprobe__blk_account_io_done: -1
    at Object.checkStatus (/home/bizconf/work/bpf-node/node_modules/bpfcc/dist/exception.js:26:11)
    at BPFModule.attachKprobe (/home/bizconf/work/bpf-node/node_modules/bpfcc/dist/index.js:87:28)
    at Object.kprobe (/home/bizconf/work/bpf-node/node_modules/bpfcc/dist/index.js:304:36)
    at BPFModule.autoload (/home/bizconf/work/bpf-node/node_modules/bpfcc/dist/index.js:309:33)
    at post (/home/bizconf/work/bpf-node/node_modules/bpfcc/dist/index.js:35:17)
    at genericLoad (/home/bizconf/work/bpf-node/node_modules/bpfcc/dist/index.js:31:19)
    at Object.loadSync (/home/bizconf/work/bpf-node/node_modules/bpfcc/dist/index.js:50:12)
    at Object.<anonymous> (/home/bizconf/work/bpf-node/test.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  code: -1
}
```

The test.ts file is here, I just copy it from bitehist.ts of example directory.

```javascript
import { loadSync } from 'bpfcc'
import { u32type } from 'bpf'

// Upload BPF to kernel
console.log('Loading program...')
const bpf = loadSync(`
    #include <uapi/linux/ptrace.h>
    #include <linux/blkdev.h>
    BPF_HISTOGRAM(dist);
    BPF_HISTOGRAM(dist_linear);
    int kprobe__blk_account_io_done(struct pt_regs *ctx, struct request *req) {
        dist.increment(bpf_log2l(req->__data_len / 1024));
        dist_linear.increment(req->__data_len / 1024);
        return 0;
    }
`)

console.log('Done! Tracing...')
const dist = bpf.getArrayMap('dist', u32type)
setInterval(() => {
    const ys = [...dist]
    const maxY = Math.max(...ys)
    const cols = 68
    const rpad = (x: string, n: number) => ' '.repeat(Math.max(n - x.length, 0)) + x.substr(0, n)
    console.log('\nDistribution:\n' + ys.map((y, i) =>
        rpad(`${y}`, 8) + ' |' + '#'.repeat(Math.round(y / maxY * cols))
    ).join('\n'))
}, 2000)
```

**Comment by lugy-bupt** [comment]
Sorry I forgot to run it with root. It works.

```
bizconf@bizconf:~/work/bpf-node$ sudo su
[sudo] password for bizconf: 
root@bizconf:/home/bizconf/work/bpf-node# node test.js
Loading program...
Done! Tracing...

Distribution:
       0 |
       4 |####################################################################
       0 |
       0 |
```
